# Production Environment Configuration
# Copy to config.prod.yaml and customize

database:
  # PostgreSQL for production
  database_type: "postgresql"
  host: "db.production.example.com"
  port: 5432
  database: "agentfarm_simulations"
  username: "${DB_USERNAME}"  # Use environment variables
  password: "${DB_PASSWORD}"
  sslmode: "require"
  pool_size: 20
  query_timeout: 60
  read_only: true

cache:
  enabled: true
  backend: "redis"  # Use Redis for production
  max_size: 1000
  ttl_seconds: 600
  redis_host: "redis.production.example.com"
  redis_port: 6379
  redis_db: 0
  redis_password: "${REDIS_PASSWORD}"
  redis_key_prefix: "mcp:prod:"

server:
  max_result_size: 50000
  default_limit: 100
  log_level: "INFO"
  environment: "production"
  structured_logging: true
  json_logs: true  # JSON logs for log aggregation
